services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mediavault-backend:latest

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mediavault-frontend:latest
